# -*- coding: utf-8 -*-
"""Copy of Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gblaxI630MaV49Ei9UusLv-q5FIq85j6

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s = "Hi there Sam!"
x=s.split()
x

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet = "Earth"
diameter = 12742
s="The diameter of {} is {} kilometers."
print(s.format(planet,diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
a=np.zeros(10)
print(a)

import numpy as np
b=np.ones(10)*5
print(b)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
a=np.arange(20,35,2)
print(a)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b),axis=None)
print(x)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

import pandas as pd
data={'Name':['Raga Varshini R','Sabari Vasan R T','Tamilselvi Kumaresan'],'Age':['20','18','52']}
a=pd.DataFrame(data)
print(a)

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import datetime
import pandas as pd
test = datetime.datetime.strptime("01/01/2023","%d/%m/%Y")
k=41
dg = pd.date_range(test,periods=k)
print(dg.strftime("%d/%m/%Y"))

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as pd
lists = [[1, 'aaa', 22],[2,'bbb', 25],[3,'ccc', 24]]
a = pd.DataFrame(lists,columns=['No','Letter','Numbers'])
print(a)